update-binary: format overlong constructs

diff --git a/src/META-INF/com/google/android/update-binary b/src/META-INF/com/google/android/update-binary
--- a/src/META-INF/com/google/android/update-binary
+++ b/src/META-INF/com/google/android/update-binary
@@ -16,7 +16,16 @@ zipfile="$3";
 ps | grep zygote | grep -v grep >/dev/null && bootmode=true || bootmode=false;
 $bootmode || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && bootmode=true;
 
-if $bootmode; then ui_print() { echo "$1" >&3; }; else ui_print() { echo "ui_print $1" >> "$outfd"; echo "ui_print" >> "$outfd"; }; fi;
+if $bootmode; then
+  ui_print() {
+    echo "$1" >&3;
+  };
+else
+  ui_print() {
+    echo "ui_print $1" >> "$outfd";
+    echo "ui_print" >> "$outfd";
+  };
+fi;
 
 log() { echo "$1"; }
 
@@ -47,7 +56,9 @@ abort() {
   uninstall_pack;
   [ -d "$filedir" ] && rm -rf "$filedir";
   [ -d "$bbdir" ] && rm -rf "$bbdir";
-  $bootmode || { if [ "$sysroot" ]; then umount "/$sysroot"; else umount "/system"; fi; }
+  $bootmode || {
+    if [ "$sysroot" ]; then umount "/$sysroot"; else umount "/system"; fi;
+  }
   sync;
   ui_print " ";
   ui_print "Installation failed!";
@@ -188,13 +199,25 @@ remove() {
       backupobject="$(dirname "$(dirname "$backupobject")")/$(basename "$backupobject")";
     }
   fi;
-  [ "$(basename "$(dirname "$removalobject")").apk" = "$(basename "$removalobject")" ] && { removalobject="$(dirname "$removalobject")"; backupobject="$(dirname "$backupobject")"; }
+  [ "$(basename "$(dirname "$removalobject")").apk" = "$(basename "$removalobject")" ] && {
+    removalobject="$(dirname "$removalobject")";
+    backupobject="$(dirname "$backupobject")";
+  }
   [ -e "$removalobject" ] || return 0;
   mkdir -p "$(dirname "$backupobject")";
   cp -rf "$removalobject" "$backupobject";
-  if [ -e "$backupobject" ]; then log "BACKUPER: Object backed up ($removalobject)"; else log "ERROR: Could not backup ($removalobject)"; fi;
+  if [ -e "$backupobject" ]; then
+    log "BACKUPER: Object backed up ($removalobject)";
+  else
+    log "ERROR: Could not backup ($removalobject)";
+  fi;
   rm -rf "$removalobject" || { log "ERROR: Could not remove ($removalobject)"; return 1; }
-  if [ -e "$removalobject" ]; then { log "ERROR: Could not remove ($removalobject)"; return 1; }; else log "REMOVER: Object removed ($removalobject)"; fi;
+  if [ -e "$removalobject" ]; then
+    log "ERROR: Could not remove ($removalobject)";
+    return 1;
+  else
+    log "REMOVER: Object removed ($removalobject)";
+  fi;
 }
 
 debloat() {
@@ -210,12 +233,27 @@ debloat() {
   [ -e "$debloatobject" ] || return 0;
   mkdir -p "$(dirname "$debloatingobject")";
   if [ "$(basename "$(dirname "$debloatingobject")").apk" = "$(basename "$debloatingobject")" ]; then
-    if touch "$(dirname "$debloatingobject")/.replace"; then log "DEBLOATER: Object directory debloated ($debloatobject)"; else { log "ERROR: Could not create replace file for object $debloatobject"; return 1; }; fi;
+    if touch "$(dirname "$debloatingobject")/.replace"; then
+      log "DEBLOATER: Object directory debloated ($debloatobject)";
+    else
+      log "ERROR: Could not create replace file for object $debloatobject";
+      return 1;
+    fi;
   elif [ -d "$debloatobject" ]; then
     mkdir -p "$debloatingobject";
-    if touch "$debloatingobject/.replace"; then log "DEBLOATER: directory debloated ($debloatobject)"; else { log "ERROR: Could not create replace file for directory $debloatobject"; return 1; }; fi;
+    if touch "$debloatingobject/.replace"; then
+      log "DEBLOATER: directory debloated ($debloatobject)";
+    else
+      log "ERROR: Could not create replace file for directory $debloatobject";
+      return 1;
+    fi;
   else
-    if echo "# This is a dummy for debloating" > "$debloatingobject"; then log "DEBLOATER: Object dummy debloated ($debloatobject)"; else { log "ERROR: Could not create dummy file for $debloatobject"; return 1; }; fi;
+    if echo "# This is a dummy for debloating" > "$debloatingobject"; then
+      log "DEBLOATER: Object dummy debloated ($debloatobject)";
+    else
+      log "ERROR: Could not create dummy file for $debloatobject";
+      return 1;
+    fi;
   fi;
 }
 
@@ -226,8 +264,16 @@ uninstall() {
   fi;
   [ "$(basename "$(dirname "$uninstallobject")").apk" = "$(basename "$uninstallobject")" ] && uninstallobject="$(dirname "$uninstallobject")";
   [ -e "$uninstallobject" ] || return 0;
-  rm -rf "$uninstallobject" || { log "ERROR: Object not uninstalled ($uninstallobject)"; return 1; }
-  if [ -e "$uninstallobject" ]; then { log "ERROR: Object not uninstalled ($uninstallobject)"; return 1; }; else log "UNINSTALLER: Object uninstalled ($uninstallobject)"; fi;
+  rm -rf "$uninstallobject" || {
+    log "ERROR: Object not uninstalled ($uninstallobject)";
+    return 1;
+  }
+  if [ -e "$uninstallobject" ]; then
+    log "ERROR: Object not uninstalled ($uninstallobject)";
+    return 1;
+  else
+    log "UNINSTALLER: Object uninstalled ($uninstallobject)";
+  fi;
 }
 
 install_dest() {
@@ -242,7 +288,11 @@ install_dest() {
   fi;
   mkdir -p "$(dirname "$destobject")";
   cp -rf "$object" "$destobject" || abort "Could not install $destobject";
-  if [ -e "$destobject" ]; then log "INSTALLER: Object installed ($object to $destobject)"; else abort "Could not install $destobject"; fi;
+  if [ -e "$destobject" ]; then
+    log "INSTALLER: Object installed ($object to $destobject)";
+  else
+    abort "Could not install $destobject";
+  fi;
   case "$destobject" in
     *.apk)
       install_lib "$destobject";
@@ -298,7 +348,11 @@ install_lib() {
       mkdir -p "$libdest";
       for lib in "$tmplibdir/lib/$archlib"/lib*.so; do
         cp -rf "$lib" "$libdest/$(basename "$lib")" || abort "Could not Install $lib for $libobject";
-        if [ -f "$libdest/$(basename "$lib")" ]; then log "INSTALLER: Installed library ($lib to $libdest)"; else abort "Could not Install $lib for $libobject"; fi;
+        if [ -f "$libdest/$(basename "$lib")" ]; then
+          log "INSTALLER: Installed library ($lib to $libdest)";
+        else
+          abort "Could not Install $lib for $libobject";
+        fi;
       done;
       break;
     fi;
@@ -393,7 +447,10 @@ if [ "$action" = "installation" ]; then
       [ "$thing" ] && remove "/$sysroot/$thing" "$backupdir/$thing";
     done;
   fi;
-  [ -d "$backupdir" ] && { perm 1023 1023 775 664 "$backupdir"; chcon -hR 'u:object_r:media_rw_data_file:s0' "$backupdir"; }
+  [ -d "$backupdir" ] && {
+    perm 1023 1023 775 664 "$backupdir";
+    chcon -hR 'u:object_r:media_rw_data_file:s0' "$backupdir";
+  }
 
   ui_print " ";
   ui_print "Extracting files...";
@@ -458,13 +515,17 @@ if [ "$action" = "installation" ]; then
   log " ";
   log "Executing other actions";
   if [ "$magisk" = "yes" ]; then
-    [ "$modprop" ] && { echo "$modprop" > "$root/module.prop" || abort "Could not create module.prop in $root"; }
+    [ "$modprop" ] && {
+      echo "$modprop" > "$root/module.prop" || abort "Could not create module.prop in $root";
+    }
     touch "$root/auto_mount" || abort "Could not create auto_mount in $root";
     if $bootmode && [ "$modulesdir" = "/data/adb/modules_update" ]; then
       modmnt="/data/adb/modules";
       mkdir -p "$modmnt/$modname";
       touch "$modmnt/$modname/update" || abort "Could not create update in $modmnt/$modname";
-      [ "$modprop" ] && { echo "$modprop" > "$modmnt/$modname/module.prop" || abort "Could not create module.prop in $modmnt/$modname"; }
+      [ "$modprop" ] && {
+        echo "$modprop" > "$modmnt/$modname/module.prop" || abort "Could not create module.prop in $modmnt/$modname";
+      }
     fi;
   fi;
 
@@ -503,7 +564,9 @@ fi;
 
 ui_print " ";
 ui_print "Unmounting...";
-$bootmode || { if [ "$sysroot" ]; then umount "/$sysroot"; else umount /system; fi; }
+$bootmode || {
+  if [ "$sysroot" ]; then umount "/$sysroot"; else umount /system; fi;
+}
 rm -rf "$filedir";
 [ -d "$bbdir" ] && rm -rf "$bbdir";
 sync;
